java_library(
  name = 'hello_lib',
  srcs = glob(['*.java']),
)

java_binary(
  name = 'HelloWorld',
  deps = [
    ':hello_lib',
  ],
  main_class = 'com.google.basics.HelloWorld',
)

java_library(
  name = 'Math',
  srcs = ['Math.java'],
  visibility = ['PUBLIC'],
)
