java_library(
  name = 'hello_lib',
  srcs = glob(['*.java']),
)

java_binary(
  name = 'HelloWorld',
  srcs = glob(['*.java']),
  srcs = [],
  main_class = 'com.lol.basics.HelloWorld',
  deps = [
    ':hello_lib',
  ],
)
