# Demonstration application for the Go language runtime.
application: carmine
module: default
version: 1
runtime: go
api_version: go1

instance_class: F4_1G

handlers:
- url: /s
  static_dir: public/
  secure: always

# Catch-all handler.
- url: /.*
  script: _go_app

# DO NOT REMOVE. This handler is required for Cloud Endpoints to work.
- url: /_ah/spi/.*
  script: _go_app

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?Tupfile$
  - ^(.*/)?Makefile$
  - ^(.*/)?Tupfile\.lua$
  - ^(.*/)?.*\.tup$
  - ^assets/$
