java_test(
  name = 'all_tests',
  srcs = glob(['*Test.java']),
  source_under_test = [
    '//src/java/com/google/basics:Math',
  ],
  deps = [
    '//src/java/com/google/basics:Math',
    '//third_party/java/hamcrest:hamcrest-core',
    '//third_party/java/hamcrest:hamcrest-library',
    '//third_party/java/junit:junit',
  ],
)
